import Foundation
import GRDB

// One post or project page. The id is written into frontmatter as cmsId.
nonisolated struct Document: DatabaseRecord, Identifiable, Equatable {
    static let databaseTableName = "documents"

    // Which folder in the site the file is written to. The database checks this one.
    enum Collection: String, Codable, CaseIterable, DatabaseValueConvertible, Sendable {
        case blog
        case projects

        static let allNames = allCases.map(\.rawValue)
    }

    // Whether the file exists on the site. modified is not a state, it is the isModified column.
    enum State: String, Codable, CaseIterable, DatabaseValueConvertible, Sendable {
        case draft
        case published

        static let allNames = allCases.map(\.rawValue)
    }

    var id: UUID
    var collection: Collection
    var slug: String?
    var title: String
    var description: String
    var bodyMd: String
    var tags: [String]
    var featured: Bool
    var publishDate: Date?
    var updatedDate: Date?
    var cover: String?
    var coverAlt: String
    var fields: DocumentFields
    var state: State
    var publishedSlug: String?
    var publishedHash: String?
    // Set only when you chose to keep the app's version over a file someone edited outside it.
    var acknowledgedHash: String?
    var publishedAt: Date?
    var createdAt: Date
    var updatedAt: Date
    // Generated by SQLite from the row, so it arrives on every read and is never written.
    var isModified: Bool

    // The column is fields_json, the property is fields, and the snake case strategy joins the two.
    enum CodingKeys: String, CodingKey {
        case id, collection, slug, title, description, bodyMd, tags, featured
        case publishDate, updatedDate, cover, coverAlt
        case fields = "fieldsJson"
        case state, publishedSlug, publishedHash, acknowledgedHash, publishedAt, createdAt, updatedAt
        case isModified
    }

    init(
        id: UUID,
        collection: Collection,
        slug: String? = nil,
        title: String = "",
        description: String = "",
        bodyMd: String = "",
        tags: [String] = [],
        featured: Bool = false,
        publishDate: Date? = nil,
        updatedDate: Date? = nil,
        cover: String? = nil,
        coverAlt: String = "",
        fields: DocumentFields = DocumentFields(),
        state: State = .draft,
        publishedSlug: String? = nil,
        publishedHash: String? = nil,
        acknowledgedHash: String? = nil,
        publishedAt: Date? = nil,
        createdAt: Date,
        updatedAt: Date,
        isModified: Bool = false
    ) {
        self.id = id
        self.collection = collection
        self.slug = slug
        self.title = title
        self.description = description
        self.bodyMd = bodyMd
        self.tags = tags
        self.featured = featured
        self.publishDate = publishDate
        self.updatedDate = updatedDate
        self.cover = cover
        self.coverAlt = coverAlt
        self.fields = fields
        self.state = state
        self.publishedSlug = publishedSlug
        self.publishedHash = publishedHash
        self.acknowledgedHash = acknowledgedHash
        self.publishedAt = publishedAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.isModified = isModified
    }

    // Written by hand rather than by Codable, because SQLite refuses a write to the generated
    // is_modified column and the id has to land as text rather than as a blob.
    func encode(to container: inout PersistenceContainer) throws {
        container["id"] = id.uuidString
        container["collection"] = collection.rawValue
        container["slug"] = slug
        container["title"] = title
        container["description"] = description
        container["body_md"] = bodyMd
        container["tags"] = try DatabaseJSON.encode(tags)
        container["featured"] = featured
        container["publish_date"] = publishDate
        container["updated_date"] = updatedDate
        container["cover"] = cover
        container["cover_alt"] = coverAlt
        container["fields_json"] = try DatabaseJSON.encode(fields)
        container["state"] = state.rawValue
        container["published_slug"] = publishedSlug
        container["published_hash"] = publishedHash
        container["acknowledged_hash"] = acknowledgedHash
        container["published_at"] = publishedAt
        container["created_at"] = createdAt
        container["updated_at"] = updatedAt
    }
}

// Everything in frontmatter that the app never filters or sorts on, so it stays in one JSON column.
nonisolated struct DocumentFields: Codable, Equatable, Sendable {
    enum ProjectStatus: String, Codable, CaseIterable, Sendable {
        case active
        case complete
        case archived
    }

    // Frontmatter the app never filters or sorts on, but must write back exactly as it found it.
    var draft: Bool?
    var aiAssisted: Bool?

    var canonicalUrl: URL?
    var role: String?
    var timeline: String?
    var status: ProjectStatus?
    var tech: [String]?
    var videoUrl: URL?
    var repoUrl: URL?
    var liveUrl: URL?
    var order: Int?

    init(
        draft: Bool? = nil,
        aiAssisted: Bool? = nil,
        canonicalUrl: URL? = nil,
        role: String? = nil,
        timeline: String? = nil,
        status: ProjectStatus? = nil,
        tech: [String]? = nil,
        videoUrl: URL? = nil,
        repoUrl: URL? = nil,
        liveUrl: URL? = nil,
        order: Int? = nil
    ) {
        self.draft = draft
        self.aiAssisted = aiAssisted
        self.canonicalUrl = canonicalUrl
        self.role = role
        self.timeline = timeline
        self.status = status
        self.tech = tech
        self.videoUrl = videoUrl
        self.repoUrl = repoUrl
        self.liveUrl = liveUrl
        self.order = order
    }
}

// The narrow row the library list reads, so no body is ever loaded to draw a list.
nonisolated struct DocumentListItem: DatabaseRow, Identifiable, Equatable {
    var id: UUID
    var collection: Document.Collection
    var slug: String?
    var title: String
    var description: String
    var tags: [String]
    var state: Document.State
    var isModified: Bool
    var updatedAt: Date

    // The one column list the list and the search query both select.
    static let selection = """
        documents.id, documents.collection, documents.slug, documents.title, \
        documents.description, documents.tags, documents.state, \
        documents.is_modified, documents.updated_at
        """
}


// The narrow row the repo scan reads, so no body is ever loaded to compare a hash.
nonisolated struct DocumentFileRef: DatabaseRow, Identifiable, Equatable, Sendable {
    var id: UUID
    var collection: Document.Collection
    var slug: String?
    var state: Document.State
    var publishedSlug: String?
    var publishedHash: String?
    var acknowledgedHash: String?

    static let selection = """
        documents.id, documents.collection, documents.slug, documents.state, \
        documents.published_slug, documents.published_hash, documents.acknowledged_hash
        """
}
